using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.IO;
using FormCore;

namespace FormCoreTest {
  [TestClass]
  public class ShareWithJS {
    public static string ProjectFrontendPath() {
      return string.Format("{0}/../../../Frontend/", AppDomain.CurrentDomain.BaseDirectory);
    }

    public static string EnumClassToJs(Type e) {
      var ret = "";
      ret += "// This file is auto generated by FormCore-Backend project, please do NOT modify from here.\n";
      ret += "export default {\n";
      foreach (var val in Enum.GetValues(e)) {
        var name = Enum.GetName(e, val);
        ret += string.Format("  {0}: {1},\n", name, (int)val);
      }
      ret += "};\n";
      return ret;
    }


    public static void Register() {
      var projectUIPath = ProjectFrontendPath();

      var jsPath = string.Format("{0}/src/Constants/", projectUIPath);

      var enumKlasses = new[] {
        typeof(FieldType),
      };
      if (projectUIPath != null && Directory.Exists(jsPath))
        foreach (var enumKlass in enumKlasses) {
          var path = string.Format("{0}/{1}.jsx", jsPath, enumKlass.Name);
          File.WriteAllText(path, EnumClassToJs(enumKlass));
        }

    }
    [TestMethod]
    public void ShareToJS() {
      Console.WriteLine(ProjectFrontendPath());
      Assert.AreEqual(true, Directory.Exists(ProjectFrontendPath()));
      Register();
    }
  }
}
